In [97]:
#importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [98]:
#reading the excel file

heritage = pd.read_excel('index2021_data.xls')
heritage

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2021 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,146.0,33.0,53.0,30.3,25.7,29.1,...,Afghanistan,38.041754,76.624,3.037,2.3484,2293.551684,11.1,2.302,38.533333,7.3
1,2,Albania,Albania,Europe,66.0,35.0,65.2,46.1,22.8,40.6,...,Albania,2.854191,39.832,2.214,3.1242,14495.078514,12.3,1.411,1281.252239,68.8
2,3,Algeria,Algeria,Middle East and North Africa,162.0,13.0,49.7,34.0,41.6,32.7,...,Algeria,43.053054,668.827,0.700,2.0600,11820.087684,11.7,1.952,1381.890090,46.3
3,4,Angola,Angola,Sub-Saharan Africa,140.0,30.0,54.2,30.3,22.8,20.4,...,Angola,31.825295,200.830,-1.503,-0.8978,6929.678158,6.9,17.079,-4098.478748,109.8
4,5,Argentina,Argentina,Americas,148.0,26.0,52.7,46.1,45.7,54.0,...,Argentina,44.938712,911.562,-2.163,-0.2650,22947.139795,9.8,53.548,6244.423000,88.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,179,Venezuela,Venezuela,Americas,177.0,32.0,24.7,7.5,15.4,15.1,...,Venezuela,28.515829,202.009,-35.000,-18.7106,5990.000000,24.0,19906.020,934.000000,232.8
180,180,Vietnam,Vietnam,Asia-Pacific,90.0,17.0,61.7,51.3,35.9,38.0,...,Vietnam,96.462106,1001.480,7.017,6.9420,8374.444328,2.0,2.797,16120.000000,42.9
181,181,Yemen,Yemen,Middle East and North Africa,NaN,NaN,NaN,16.5,19.7,17.0,...,Yemen,29.161922,72.133,2.100,-7.9180,1910.000000,NaN,10.000,-370.982778,56.8
182,182,Zambia,Zambia,Sub-Saharan Africa,159.0,39.0,50.4,37.2,26.2,30.5,...,Zambia,17.861030,75.857,1.520,3.1512,3623.699395,11.4,9.800,753.200000,85.7
183,183,Zimbabwe,Zimbabwe,Sub-Saharan Africa,174.0,46.0,39.5,32.6,32.0,21.3,...,Zimbabwe,14.645468,39.739,-8.276,0.4916,2953.484113,5.0,255.292,280.000000,11.0

In [99]:
# exploring the data set shape
heritage.shape

(184, 34)

In [100]:
#exploring the data types - no need to convert any data type column
heritage.dtypes

CountryID                        int64
Country Name                    object
WEBNAME                         object
Region                          object
World Rank                     float64
Region Rank                    float64
2021 Score                     float64
Property Rights                float64
Judical Effectiveness          float64
Government Integrity           float64
Tax Burden                     float64
Gov't Spending                 float64
Fiscal Health                  float64
Business Freedom               float64
Labor Freedom                  float64
Monetary Freedom               float64
Trade Freedom                  float64
Investment Freedom             float64
Financial Freedom              float64
Tariff Rate (%)                float64
Income Tax Rate (%)            float64
Corporate Tax Rate (%)         float64
Tax Burden % of GDP            float64
Gov't Expenditure % of GDP     float64
Country                         object
Population (Millions)          float64
GDP (Billions, PPP)            float64
GDP Growth Rate (%)            float64
5 Year GDP Growth Rate (%)     float64
GDP per Capita (PPP)           float64
Unemployment (%)               float64
Inflation (%)                  float64
FDI Inflow (Millions)          float64
Public Debt (% of GDP)         float64
dtype: object

# working with the data frame

In [101]:
# deleting country id and webname

del heritage['CountryID'], heritage['WEBNAME'], heritage['Country']

In [103]:
# the two columns were deleted
heritage.shape

(184, 31)

In [86]:
# setting Country Name as index

heritage.set_index('Country Name')

,Region,World Rank,Region Rank,2021 Score,Property Rights,Judical Effectiveness,Government Integrity,Tax Burden,Gov't Spending,Fiscal Health,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia-Pacific,146.0,33.0,53.0,30.3,25.7,29.1,91.1,76.1,99.9,...,Afghanistan,38.041754,76.624,3.037,2.3484,2293.551684,11.1,2.302,38.533333,7.3
Albania,Europe,66.0,35.0,65.2,46.1,22.8,40.6,89.0,74.6,86.6,...,Albania,2.854191,39.832,2.214,3.1242,14495.078514,12.3,1.411,1281.252239,68.8
Algeria,Middle East and North Africa,162.0,13.0,49.7,34.0,41.6,32.7,67.2,55.4,49.1,...,Algeria,43.053054,668.827,0.700,2.0600,11820.087684,11.7,1.952,1381.890090,46.3
Angola,Sub-Saharan Africa,140.0,30.0,54.2,30.3,22.8,20.4,87.3,86.9,77.9,...,Angola,31.825295,200.830,-1.503,-0.8978,6929.678158,6.9,17.079,-4098.478748,109.8
Argentina,Americas,148.0,26.0,52.7,46.1,45.7,54.0,70.4,52.8,38.4,...,Argentina,44.938712,911.562,-2.163,-0.2650,22947.139795,9.8,53.548,6244.423000,88.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,Americas,177.0,32.0,24.7,7.5,15.4,15.1,71.1,61.5,0.0,...,Venezuela,28.515829,202.009,-35.000,-18.7106,5990.000000,24.0,19906.020,934.000000,232.8
Vietnam,Asia-Pacific,90.0,17.0,61.7,51.3,35.9,38.0,80.3,86.0,82.8,...,Vietnam,96.462106,1001.480,7.017,6.9420,8374.444328,2.0,2.797,16120.000000,42.9
Yemen,Middle East and North Africa,NaN,NaN,NaN,16.5,19.7,17.0,NaN,95.6,48.9,...,Yemen,29.161922,72.133,2.100,-7.9180,1910.000000,NaN,10.000,-370.982778,56.8
Zambia,Sub-Saharan Africa,159.0,39.0,50.4,37.2,26.2,30.5,71.1,78.5,5.3,...,Zambia,17.861030,75.857,1.520,3.1512,3623.699395,11.4,9.800,753.200000,85.7
Zimbabwe,Sub-Saharan Africa,174.0,46.0,39.5,32.6,32.0,21.3,63.4,89.4,58.8,...,Zimbabwe,14.645468,39.739,-8.276,0.4916,2953.484113,5.0,255.292,280.000000,11.0

In [137]:
contries_nan = heritage[heritage.isna().any(axis=1)]
contries_nan

,Country Name,Region,World Rank,Region Rank,2021 Score,Property Rights,Judical Effectiveness,Government Integrity,Tax Burden,Gov't Spending,...,Gov't Expenditure % of GDP,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
42,Cuba,Americas,176.0,31.0,28.1,27.7,10.0,48.7,47.1,0.0,...,64.611333,11.333483,159.440,0.500,1.8082,14080.000000,1.6,5.600,NaN,51.9
47,Dominica,Americas,147.0,25.0,53.0,51.2,66.3,51.0,70.0,7.4,...,55.557333,0.071808,0.848,9.205,0.0358,12659.344515,NaN,1.607,32.551852,83.3
77,Iraq,Middle East and North Africa,NaN,NaN,NaN,44.8,11.0,22.0,NaN,65.3,...,34.014333,39.309783,708.265,3.914,3.7184,11332.141475,12.8,-0.199,-3075.600000,51.4
86,Kiribati,Asia-Pacific,171.0,39.0,44.4,44.8,33.1,27.9,70.7,0.0,...,119.297667,0.117606,0.251,2.297,4.2084,2369.465528,NaN,-1.881,0.482545,23.0
87,"Korea, North",Asia-Pacific,178.0,40.0,5.2,27.7,5.0,20.2,0.0,0.0,...,NaN,25.666161,40.000,2.300,-0.5000,1700.000000,25.6,NaN,25.759139,NaN
97,Libya,Middle East and North Africa,NaN,NaN,NaN,16.5,19.7,21.0,NaN,0.0,...,94.491667,6.777452,83.540,9.890,14.2742,15803.056375,NaN,4.563,NaN,5.6
98,Liechtenstein,Europe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.038019,NaN,NaN,NaN,NaN,1.7,0.900,NaN,NaN
145,Seychelles,Sub-Saharan Africa,60.0,4.0,66.3,65.3,51.6,64.4,76.9,60.9,...,36.079667,0.097625,3.060,3.901,4.3010,30259.961030,NaN,1.807,125.539658,58.3
151,Somalia,Sub-Saharan Africa,NaN,NaN,NaN,27.8,23.3,11.5,NaN,NaN,...,NaN,15.442905,12.655,2.900,2.6878,NaN,11.4,NaN,447.000000,NaN
159,Syria,Middle East and North Africa,NaN,NaN,NaN,42.5,19.7,25.9,NaN,NaN,...,NaN,17.070135,67.100,4.800,-0.3800,4030.000000,43.5,11.200,NaN,93.7
181,Yemen,Middle East and North Africa,NaN,NaN,NaN,16.5,19.7,17.0,NaN,95.6,...,12.166000,29.161922,72.133,2.100,-7.9180,1910.000000,NaN,10.000,-370.982778,56.8

In [133]:
len(contries_nan)

11

In [145]:
heritage.shape

(173, 31)

In [147]:
# the 11 countries with NaN values was dropped from 
# the main data frame "heritage" and they are stored in the variable "contries_nan"
heritage.dropna(inplace=True)

In [152]:
#first view of the clean data and setting again the index
heritage.set_index('Country Name')

,Region,World Rank,Region Rank,2021 Score,Property Rights,Judical Effectiveness,Government Integrity,Tax Burden,Gov't Spending,Fiscal Health,...,Gov't Expenditure % of GDP,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia-Pacific,146.0,33.0,53.0,30.3,25.7,29.1,91.1,76.1,99.9,...,28.222333,38.041754,76.624,3.037,2.3484,2293.551684,11.1,2.302,38.533333,7.3
Albania,Europe,66.0,35.0,65.2,46.1,22.8,40.6,89.0,74.6,86.6,...,29.117000,2.854191,39.832,2.214,3.1242,14495.078514,12.3,1.411,1281.252239,68.8
Algeria,Middle East and North Africa,162.0,13.0,49.7,34.0,41.6,32.7,67.2,55.4,49.1,...,38.500000,43.053054,668.827,0.700,2.0600,11820.087684,11.7,1.952,1381.890090,46.3
Angola,Sub-Saharan Africa,140.0,30.0,54.2,30.3,22.8,20.4,87.3,86.9,77.9,...,20.908000,31.825295,200.830,-1.503,-0.8978,6929.678158,6.9,17.079,-4098.478748,109.8
Argentina,Americas,148.0,26.0,52.7,46.1,45.7,54.0,70.4,52.8,38.4,...,39.646000,44.938712,911.562,-2.163,-0.2650,22947.139795,9.8,53.548,6244.423000,88.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vanuatu,Asia-Pacific,97.0,18.0,60.5,53.3,34.1,39.5,96.8,61.7,94.9,...,35.732000,0.299882,0.851,2.910,2.7516,3273.914944,4.4,2.098,41.000000,50.7
Venezuela,Americas,177.0,32.0,24.7,7.5,15.4,15.1,71.1,61.5,0.0,...,35.827333,28.515829,202.009,-35.000,-18.7106,5990.000000,24.0,19906.020,934.000000,232.8
Vietnam,Asia-Pacific,90.0,17.0,61.7,51.3,35.9,38.0,80.3,86.0,82.8,...,21.625667,96.462106,1001.480,7.017,6.9420,8374.444328,2.0,2.797,16120.000000,42.9
Zambia,Sub-Saharan Africa,159.0,39.0,50.4,37.2,26.2,30.5,71.1,78.5,5.3,...,26.761000,17.861030,75.857,1.520,3.1512,3623.699395,11.4,9.800,753.200000,85.7
Zimbabwe,Sub-Saharan Africa,174.0,46.0,39.5,32.6,32.0,21.3,63.4,89.4,58.8,...,18.826333,14.645468,39.739,-8.276,0.4916,2953.484113,5.0,255.292,280.000000,11.0

In [165]:
heritage2 = heritage.set_index('Country Name')

ValueError: level name Region is not the name of the index

# gathering data

In [178]:
#counting the number of countries grouping by its region
heritage2.groupby(['Region'])['World Rank'].count()

Region
Americas                        30
Asia-Pacific                    38
Europe                          45
Middle East and North Africa    14
Sub-Saharan Africa              46
Name: World Rank, dtype: int64

In [182]:
totNcountries = heritage2.shape[0]
ameNcoutnries = heritage2.groupby(['Region'])['World Rank'].count()[0]
apNcoutnries = heritage2.groupby(['Region'])['World Rank'].count()[1]
euNcoutnries = heritage2.groupby(['Region'])['World Rank'].count()[2]
mnaNcoutnries = heritage2.groupby(['Region'])['World Rank'].count()[3]
ssaNcoutnries = heritage2.groupby(['Region'])['World Rank'].count()[4]

In [186]:
#organizing the number of countries by region is a dict
countries = {'Americas': ameNcoutnries,
            'Asia-Pacific':apNcoutnries,
            'Europe':euNcoutnries,
            'Middle East and North Africa':mnaNcoutnries,
            'Sub-Saharan Africa':ssaNcoutnries,}
countries

{'Americas': 30,
 'Asia-Pacific': 38,
 'Europe': 45,
 'Middle East and North Africa': 14,
 'Sub-Saharan Africa': 46}

In [189]:
heritage2.groupby(['Region'])['World Rank'].mean().sort_values()

Region
Europe                           44.466667
Middle East and North Africa     85.857143
Americas                         89.766667
Asia-Pacific                     92.684211
Sub-Saharan Africa              125.673913
Name: World Rank, dtype: float64

###########
ideias
começar a escrever medium
up no github
###########